"""empty message

Revision ID: 82e786462bc5
Revises: b3a8c9b40dee
Create Date: 2020-03-10 19:16:20.010688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82e786462bc5'
down_revision = 'b3a8c9b40dee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('profilepic', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'profilepic')
    # ### end Alembic commands ###
